version: "3"
services:
  offender-categorisation-int-db:
    image: postgres:16
    networks:
      - hmpps
    container_name: oc-api-int-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=form-builder
      - POSTGRES_USER=form-builder
      - POSTGRES_DB=form-builder

  localstack:
    image: localstack/localstack:3.0.0
    ports:
      - "4566:4566"
    networks:
      - hmpps
    container_name: localstack
    environment:
      - SERVICES=${SERVICES-sqs,s3,sns}
      - DEBUG=${DEBUG- }
      - PERSISTENCE=${DATA_DIR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - AWS_DEFAULT_REGION=eu-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  setup-localstack-resources:
    image: jetbrainsinfra/aws-cli
    networks:
      - hmpps
    depends_on:
      - localstack
    volumes:
      - ./dev_env:/project/dev_env
    container_name: oc-api-setup-aws-resources
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=eu-west-2
    entrypoint: /bin/sh -c
    command: >
      "
        while [[ $$(curl -s -o /dev/null -w ''%{http_code}'' localstack:4566) != "200" ]]; do
          echo 'offender-categorisation AWS - awaiting localstack service start'
          sleep 10
        done

        aws --endpoint-url=http://localstack:4566 s3 mb s3://testbucket
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name nomis_queue
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name delius_queue
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name nomis_dlq
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name delius_dlq
        aws --endpoint-url=http://localstack:4566 sqs list-queues
        aws --endpoint-url=http://localstack:4566 s3 ls

        exit 0
      "

networks:
  hmpps:
