version: "3"
services:
  hmpps-offender-categorisation-api:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-offender-categorisation-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  form-db:
    image: postgres:15
    networks:
      - hmpps
    container_name: api-form-builder-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=form-builder
      - POSTGRES_USER=form-builder
      - POSTGRES_DB=form-builder

  localstack-oc-api:
    image: localstack/localstack:3.6
    networks:
      - hmpps
    container_name: localstack-oc-api
    ports:
      - "4566-4597:4566-4597"
      - "4610-4659:4610-4659"
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - GATEWAY_LISTEN=0.0.0.0:4666
      - EXTERNAL_SERVICE_PORTS_START=4610
      - EXTERNAL_SERVICE_PORTS_END=4659
      - MAIN_CONTAINER_NAME=localstack-api
      - AWS_ENDPOINT_URL=http://localhost:4666
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: awslocal sqs list-queues
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  hmpps:
