hmpps.sqs:
  provider: localstack
  queues:
    domainevents:
      queueName: "oc_api_queue"
      dlqName: "oc_api_queue"
      subscribeTopicId: domainevents
      subscribeFilter: "{\"eventType\":[\"prisoner-offender-search.prisoner.released\", \"prisoner-offender-search.prisoner.received\", \"prison-offender-events.prisoner.merged\"]}"
      dlqMaxReceiveCount: 3
      visibilityTimeout: 120
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}