spring:
  datasource:
    url: 'jdbc:h2:mem:form-builder;MODE=PostgreSQL'
    username: sa
    password:

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

  flyway:
    enabled: true
    locations: classpath:db/migration/common

  h2:
    console:
      enabled: false
  jpa:
    show-sql: false

# It won't use this, as the resource server uses a local file for its JWT public key but it needs a value.
hmpps:
  auth:
    token:
      url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

prisoner:
  search:
    api:
      endpoint:
        url: "https://prisoner-search-dev.prison.service.justice.gov.uk"
