server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

hmpps:
  auth:
    url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    token:
      url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token"

prisoner:
  search:
    api:
      endpoint:
        url: "https://prisoner-search-dev.prison.service.justice.gov.uk"

prison:
  api:
    endpoint:
      url: "https://prison-api-dev.prison.service.justice.gov.uk"

manage:
  adjudications:
    api:
      endpoint:
        url: "https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk"
  offences:
    api:
      endpoint:
        url: "https://manage-offences-api-dev.hmpps.service.justice.gov.uk"

assess:
  risks:
    and:
      needs:
        api:
          endpoint:
            url: "https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk"

probation:
  search:
    api:
      endpoint:
        url: "https://probation-offender-search-dev.hmpps.service.justice.gov.uk"

# Update to your personal token with correct permissions
api:
  client:
    admin:
      id: dummy
      secret: dummy

hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4666
  queues:
    domaineventsqueue:
      queueName: domainevents-queue
      dlqName: domainevents-queue-dlq
      subscribeTopicId: domainevents
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents-topic

s3:
  serviceEndpointOverride: http://localhost:4572
  bucketName: testbucket
  region: eu-west-2
  path:
    viper: ${s3.bucketName}/viper