server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

hmpps:
  auth:
    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

prisoner:
  search:
    api:
      endpoint:
        url: "https://prisoner-search-dev.prison.service.justice.gov.uk"

prison:
  api:
    endpoint:
      url: "https://prison-api-dev.prison.service.justice.gov.uk"

manage:
  adjudications:
    api:
      endpoint:
        url: "https://manage-adjudications-api-dev.prison.service.justice.gov.uk"

# Update to your personal token with correct permissions
api:
  client:
    admin:
      id: something
      secret: something
