spring:
  datasource:
    url: 'jdbc:h2:mem:form-builder;MODE=PostgreSQL'
    username: sa
    password:

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

  flyway:
    enabled: true
    locations: classpath:db/migration/common

  h2:
    console:
      enabled: false
  jpa:
    show-sql: false

# It won't use this, as the resource server uses a local file for its JWT public key but it needs a value.
hmpps:
  auth:
    token:
      url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token"

prisoner:
  search:
    api:
      endpoint:
        url: "https://prisoner-search-dev.prison.service.justice.gov.uk"

prison:
  api:
    endpoint:
      url: "https://prison-api-dev.prison.service.justice.gov.uk"

manage:
  adjudications:
    api:
      endpoint:
        url: "https://manage-adjudications-api-dev.prison.service.justice.gov.uk"
  offences:
    api:
      endpoint:
        url: "https://manage-offences-api-dev.hmpps.service.justice.gov.uk"

assess:
  risks:
    and:
      needs:
        api:
          endpoint:
            url: "https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk"

probation:
  search:
    api:
      endpoint:
        url: "https://probation-offender-search-dev.hmpps.service.justice.gov.uk"


hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4666
  queues:
    domaineventsqueue:
      queueName: domainevents-queue
      dlqName: domainevents-queue-dlq
      subscribeTopicId: domainevents
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents-topic

