#
# The "-flyway" profile is for running the API service locally against it's own pre-existing
# docker containers that are listening on known port numbers for hmpps-auth (8090) and
# a postgres database (5432).
#

# Most values are inherited from - application.yml - except the following:
spring:
  flyway:
    locations: classpath:/migration/common,/migration/{vendor}
    url: ${spring.datasource.url}
    user: ${DB_USER}
    password: ${DB_PASS}
    enabled: true
