package uk.gov.justice.digital.hmpps.hmppsoffendercategorisationapi.model.enum

enum class PrsIneligibilityReason {
  CATEGORY,
  TIME_LEFT_TO_SERVE,
  INCENTIVE_LEVEL,
  ESCAPE,
  OFFENCE_VIOLENCE,
  OFFENCE_MURDER_T3,
  OFFENCE_TERRORISM,
  OFFENCE_NATIONAL_SECURITY,
  OFFENCE_DOMESTIC_ABUSE_T3,
  OFFENCE_DOMESTIC_ABUSE,
  OFFENCE_SEXUAL_T3,
  OFFENCE_SEXUAL,
}
