INSERT INTO licences
(id, licence, booking_id, stage, "version", transition_date, vary_version, additional_conditions_version, standard_conditions_version, prison_number)
VALUES(1530, '{"eligibility": {"crdTime": {"decision": "No"}, "excluded": {"decision": "No"}, "suitability": {"decision": "No"}}, "bassReferral": {"bassRequest": {"bassRequested": "No"}}, "proposedAddress": {"optOut": {"decision": "No"}, "curfewAddress": {"occupier": {"name": "Some Duty Officer", "isOffender": "Yes", "relationship": ""}, "postCode": "LS1 2AA", "residents": [], "telephone": "44000000000", "addressTown": "Leeds", "addressLine1": "123 Approved Premises Street 2", "addressLine2": "prisoner had requested BASS address", "additionalInformation": "", "residentOffenceDetails": "", "cautionedAgainstResident": "No"}, "addressProposed": {"decision": "Yes"}}}'::jsonb, 10, 'PROCESSING_RO', 1, '2021-08-06 15:06:37.188', 0, '1', '2', 'A1234AA');


INSERT INTO licence_versions
(id, "timestamp", licence, booking_id, "version", "template", vary_version, prison_number)
VALUES(422, '2023-10-03 11:01:35.913', '{"risk": {"riskManagement": {"version": "3", "emsInformation": "No", "pomConsultation": "Yes", "mentalHealthPlan": "No", "unsuitableReason": "", "hasConsideredChecks": "Yes", "manageInTheCommunity": "Yes", "emsInformationDetails": "", "riskManagementDetails": "", "proposedAddressSuitable": "Yes", "awaitingOtherInformation": "No", "nonDisclosableInformation": "No", "nonDisclosableInformationDetails": "", "manageInTheCommunityNotPossibleReason": ""}}, "curfew": {"firstNight": {"firstNightFrom": "15:00", "firstNightUntil": "07:00"}, "curfewHours": {"allFrom": "19:00", "allUntil": "07:00", "fridayFrom": "19:00", "mondayFrom": "19:00", "sundayFrom": "19:00", "fridayUntil": "07:00", "mondayUntil": "07:00", "sundayUntil": "07:00", "tuesdayFrom": "19:00", "saturdayFrom": "19:00", "thursdayFrom": "19:00", "tuesdayUntil": "07:00", "saturdayUntil": "07:00", "thursdayUntil": "07:00", "wednesdayFrom": "19:00", "wednesdayUntil": "07:00", "daySpecificInputs": "No"}}, "victim": {"victimLiaison": {"decision": "No"}}, "approval": {"release": {"decision": "Yes", "decisionMaker": "AAAAA", "reasonForDecision": "hfdtuc"}, "consideration": {"decision": "Yes"}}, "document": {"template": {"decision": "hdc_ap", "offenceCommittedBeforeFeb2015": "No"}}, "reporting": {"reportingInstructions": {"name": "sam", "postcode": "AA BRD", "telephone": "47450", "townOrCity": "Sheffield", "organisation": "crc", "reportingDate": "12/12/2023", "reportingTime": "12:12", "buildingAndStreet1": "10", "buildingAndStreet2": "street"}}, "eligibility": {"crdTime": {"decision": "No"}, "excluded": {"decision": "No"}, "suitability": {"decision": "No"}}, "finalChecks": {"onRemand": {"decision": "No"}, "segregation": {"decision": "No"}, "seriousOffence": {"decision": "No"}, "confiscationOrder": {"decision": "No"}, "undulyLenientSentence": {"decision": "No"}}, "bassReferral": {"bassOffer": {"bassArea": "hhh", "postCode": "AA AA", "telephone": "11111", "addressTown": "Sheffield", "addressLine1": "10", "addressLine2": "street", "bassAccepted": "Yes", "bassOfferDetails": ""}, "bassRequest": {"specificArea": "No", "bassRequested": "Yes", "additionalInformation": ""}, "bassAreaCheck": {"bassAreaReason": "", "bassAreaCheckSeen": "true", "approvedPremisesRequiredYesNo": "No"}}, "proposedAddress": {"optOut": {"decision": "No"}, "addressProposed": {"decision": "No"}}, "licenceConditions": {"standard": {"additionalConditionsRequired": "No"}}}'::jsonb, 10, 29, 'hdc_ap', 0, 'A1234AA');
INSERT INTO licence_versions
(id, "timestamp", licence, booking_id, "version", "template", vary_version, prison_number)
VALUES(396, '2023-03-08 11:27:45.257', '{"risk": {"riskManagement": {"version": "2", "emsInformation": "Yes", "unsuitableReason": "", "hasConsideredChecks": "Yes", "emsInformationDetails": "Test.", "riskManagementDetails": "", "proposedAddressSuitable": "Yes", "awaitingOtherInformation": "No", "nonDisclosableInformation": "No", "nonDisclosableInformationDetails": ""}}, "curfew": {"firstNight": {"firstNightFrom": "15:00", "firstNightUntil": "07:00"}, "curfewHours": {"allFrom": "19:00", "allUntil": "07:00", "fridayFrom": "19:00", "mondayFrom": "19:00", "sundayFrom": "19:00", "fridayUntil": "07:00", "mondayUntil": "07:00", "sundayUntil": "07:00", "tuesdayFrom": "19:00", "saturdayFrom": "19:00", "thursdayFrom": "19:00", "tuesdayUntil": "07:00", "saturdayUntil": "07:00", "thursdayUntil": "07:00", "wednesdayFrom": "19:00", "wednesdayUntil": "07:00", "daySpecificInputs": "No"}, "approvedPremises": {"required": "No"}, "curfewAddressReview": {"consent": "Yes", "electricity": "Yes", "homeVisitConducted": "Yes", "addressReviewComments": "Test."}}, "victim": {"victimLiaison": {"decision": "No"}}, "approval": {"release": {"decision": "Yes", "decisionMaker": "Tim Mccluskey", "reasonForDecision": ""}}, "document": {"template": {"decision": "hdc_ap", "offenceCommittedBeforeFeb2015": "No"}}, "reporting": {"reportingInstructions": {"name": "Bob Smith", "postcode": "1111 1AD", "telephone": "01234 123456", "townOrCity": "Blackburn", "organisation": "Blackburn NPS", "reportingDate": "28/03/2023", "reportingTime": "12:00", "buildingAndStreet1": "10 York Street", "buildingAndStreet2": ""}}, "eligibility": {"crdTime": {"decision": "No"}, "excluded": {"decision": "No"}, "suitability": {"decision": "No"}}, "finalChecks": {"onRemand": {"decision": "No"}, "seriousOffence": {"decision": "No"}, "confiscationOrder": {"decision": "No"}}, "bassReferral": {"bassRequest": {"bassRequested": "No"}}, "proposedAddress": {"optOut": {"decision": "No"}, "curfewAddress": {"occupier": {"name": "Bob Bobson", "relationship": "Father"}, "postCode": "AA1 1JJ", "residents": [], "telephone": "01234 111111", "addressTown": "Blackburn", "addressLine1": "10 Blackburn Road", "addressLine2": "", "additionalInformation": "", "residentOffenceDetails": "", "cautionedAgainstResident": "No"}, "addressProposed": {"decision": "Yes"}}, "licenceConditions": {"bespoke": [], "standard": {"additionalConditionsRequired": "Yes"}, "additional": {"CAMERA_APPROVAL": {}}, "conditionsSummary": {"additionalConditionsJustification": "Why they added additional condition here."}}}'::jsonb, 20, 3, 'hdc_ap', 0, 'A1234AA');


INSERT INTO audit
(id, "timestamp", "user", "action", details)
VALUES(33437, '2023-05-05 15:56:01.908', 'USER_ADM', 'UPDATE_SECTION', '{"path": "/hdc/eligibility/excluded/10", "bookingId": "10", "userInput": {"decision": "No"}}'::jsonb);
INSERT INTO audit
(id, "timestamp", "user", "action", details)
VALUES(33438, '2023-05-05 15:56:02.684', 'USER_ADM', 'UPDATE_SECTION', '{"path": "/hdc/eligibility/suitability/20", "bookingId": "20", "userInput": {"decision": "No"}}'::jsonb);
INSERT INTO audit
(id, "timestamp", "user", "action", details)
VALUES(33440, '2023-05-05 15:56:08.566', 'USER_ADM', 'UPDATE_SECTION', '{"path": "/hdc/proposedAddress/curfewAddressChoice/30", "bookingId": "30", "userInput": {"decision": "Address"}}'::jsonb);

