apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-prs-eligibility-investigation
spec:
  schedule: "{{ .Values.cron.poll_prisoners_risk_profile_schedule }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      template:
        spec:
          containers:
            - name: poll-prisoners-risk-profile
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop: ["ALL"]
              args:
                - /bin/sh
                - -c
                - curl --retry 2 http://hmpps-offender-categorisation-api/prisoner-risk-calculation/poll-prisons
          restartPolicy: Never