apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-prs-eligibility-investigation
spec:
  schedule: "{{ .Values.cron.report_prs_eligibility_investigation_schedule }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: report-prs-eligibility-investigation
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop: ["ALL"]
              args:
                - /bin/sh
                - -c
                - curl --retry 2 http://hmpps-offender-categorisation-api/prs-eligibility/report
          restartPolicy: Never