---
# Per environment values which override defaults in hmpps-offender-categorisation-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-offender-categorisation-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    HMPPS_AUTH_TOKEN_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token
    PRISONER_SEARCH_API_ENDPOINT_URL: https://prisoner-search-dev.prison.service.justice.gov.uk

  namespace_secrets:
    hmpps-offender-categorisation-api-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-offender-categorisation-api-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "sqs_queue_name"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: dps-sed-alerts-nonprod
