---
# Per environment values which override defaults in hmpps-offender-categorisation-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-offender-categorisation-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    HMPPS_AUTH_TOKEN_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token
    PRISONER_SEARCH_API_ENDPOINT_URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    PRISON_API_ENDPOINT_URL: https://prison-api-dev.prison.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_API_ENDPOINT_URL: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk
    ASSESS_RISKS_AND_NEEDS_API_ENDPOINT_URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
    MANAGE_OFFENCES_API_ENDPOINT_URL: https://manage-offences-api-dev.hmpps.service.justice.gov.uk
    PROBATION_SEARCH_API_ENDPOINT_URL: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

  namespace_secrets:
    offender-categorisation-api-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "name"
    offender-categorisation-api-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "name"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: dps-sed-alerts-nonprod
  sqsAlertsQueueNames:
    - "offender_categorisation_api_queue_for_domain_events"
    - "offender_categorisation_api_queue_for_domain_events_dead_letter_queue"
